//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimApp.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientStat
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public Nullable<int> orders { get; set; }
        public Nullable<double> spent { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
