//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimApp.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public int id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> preset_id { get; set; }
        public int group_id { get; set; }
    
        public virtual OrderGroup OrderGroup { get; set; }
        public virtual PresetGroup PresetGroup { get; set; }
        public virtual Services Services { get; set; }
    }
}
