//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimApp.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string article { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public double count { get; set; }
        public int unit_id { get; set; }
        public double price { get; set; }
        public int category_id { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
